### PR TITLE
Access system properties

### PR DESCRIPTION
**Pull request by hakanostrom**
Makes it possible to access system properties of database by using query() function. Se readme changes.

Adresses issue #32 and #42.

### CODE REVIEW

**Comment by TerryMooreII** [comment]
Cool, so this allow you access these properties without having to explicitly allow/include them in the azure endpoint like the link in #32 states?  
Also where did these number come from?
//__createdAt: 1    
//__updatedAt: 2    
//__version: 4    
//All: 65535    
//None: 0

**Comment by hakanostrom** [comment]
Exactly, it allows for the client to ask for them. The resulting request will look something like this
`http://my-ams-site.azure-mobile.net/tables/MyTable?__systemProperties=*`

The numbers are the values taken from the constants in the collection
`WindowsAzure.MobileServiceTable.SystemProperties`
exposed by the Azure mobile service client api (hinted from #32).

**Comment by TerryMooreII** [comment]
Awesome, I will merge that tonight when I get home from work and update bower.  
Also what version of the Azure client are you using?  I want to update the link in the readme,md to point to the latest version of the windows azure client.

**Comment by hakanostrom** [comment]
I am using 1.2.5 (`ajax.aspnetcdn.com/ajax/mobileservices/MobileServices.Web-1.2.5.min.js`)

However I see now that the newest version is 1.2.7, so I will change to that.

**Comment by hakanostrom** [comment]
Github:
https://github.com/Azure/azure-mobile-services

Changelog:
https://github.com/Azure/azure-mobile-services/blob/master/CHANGELOG.javascript.md

**Pull request merged**
